on join:
    send "CheezSurv1 has been archived. You can look at anything you want, but you cannot touch. | Use /dim to go to different dimensions"

every second:
    loop all players:
        send action bar "CheezSurv1 has been archived. | /dim to change dimensions" to loop-player
        set gamemode of loop-player to spectator

command /dimension [<text>]:
    aliases: /dim
    trigger:
        if arg-1 is not set:
            send "/dim <o|n|e>%nl%/dim e §7to go to the end"
            stop
        if arg-1 is "o" or "n" or "e":
            teleport player to spawn point of "world" if arg-1 is "o"
            teleport player to spawn point of "world_nether" if arg-1 is "n"
            teleport player to spawn point of "world_the_end" if arg-1 is "e"
        else:
            send "/dim <o|n|e>%nl%/dim e §7to go to the end"