options:
  cocaine: sugar named "§rCocaine" with lore "§7CheezSurv Authentic Drugglez™"
  weed: tall grass named "§rMarijuana" with lore "§7CheezSurv Authentic Drugglez™"

  cocaineDuration: 45
  weedDuration: 30

command /drugglez:
  executable by: players
  trigger:
    if player is not op:
      send "§cInsufficient permissions!"
      stop
    
    open chest with 1 row named "CheezSurv Authentic Drugglez™" to player
    wait 1 tick
    format slot 0 of player with {@cocaine} to run [give player 64 of {@cocaine}]
    format slot 1 of player with {@weed} to run [give player 64 of {@weed}]

command /drugeffects <player=%player%>:
  trigger:
    # if {drug_max_health.%arg-1%} is not set:
    #   send "§7%arg-1% §7is not experiencing druggle effects on their max health."
    #   stop
    send "%arg-1%'s max health is at %{drug_max_health.%arg-1%} otherwise ""default""% and will wear off in %{drug_max_health.%arg-1%.timer} otherwise ""-1""% seconds."
    send "%arg-1%'s absorption will wear off in %{drug_absorption.%arg-1%.timer} otherwise ""-1""% seconds."

every second in world "world":
  loop all players:
    if {drug_max_health.%loop-player%} is not set:
      max health of loop-player < 10
      set max health of loop-player to 10
      continue
    if {drug_max_health.%loop-player%.timer} <= 0:
      delete {drug_max_health.%loop-player%.timer}
      delete {drug_max_health.%loop-player%}
      continue
    remove 1 from {drug_max_health.%loop-player%.timer}
    if max health of loop-player > {drug_max_health.%loop-player%}:
      set max health of loop-player to {drug_max_health.%loop-player%}
  
  loop all players:
    if {drug_absorption.%loop-player%.timer} = 0:
      set absorption hearts of loop-player to 0
    if {drug_absorption.%loop-player%.timer} < -1:
      set {drug_absorption.%loop-player%.timer} to -1
      continue
    remove 1 from {drug_absorption.%loop-player%.timer}



on death:
  set {drug_max_health.%player%.timer} to 0
  set {drug_absorption.%player%.timer} to 0
    


on right click:
  if player's tool is {@cocaine}:
    cancel event
    remove 1 from item amount of player's tool
    apply speed 3 to player for {@cocaineDuration} seconds
    apply strength 3 to player for {@cocaineDuration} seconds
    apply haste 3 to player for {@cocaineDuration} seconds

    set {drug_max_health.%player%} to 8
    add {@cocaineDuration} to {drug_max_health.%player%.timer}

    set absorption hearts of player to 4
    add {@cocaineDuration} to {drug_absorption.%player%.timer}

    send "§eAdded {@cocaineDuration} seconds to the effects of the cocaine." to player

  if player's tool is {@weed}:
    cancel event
    remove 1 from item amount of player's tool
    apply slowness 1 to player for {@weedDuration} seconds
    apply hunger 1 to player for {@weedDuration} seconds
    apply strength 2 to player for {@weedDuration} seconds
    apply jump boost 2 to player for {@weedDuration} seconds
    if chance of 25%:
      apply mining fatigue 1 to player for {@weedDuration} seconds
    apply nausea 1 to player for 3 seconds

    set {drug_max_health.%player%} to 9
    add {@weedDuration} to {drug_max_health.%player%.timer}

    set absorption hearts of player to 2
    add {@weedDuration} to {drug_absorption.%player%.timer}

    send "§eAdded {@weedDuration} seconds to the effects of the marijuana." to player