# command /leash:
#   trigger:
    # if player's tool is not lead:
    #   send "Please hold a lead to leash a villager."
    # leash player's target entity to player

on damage:
  victim is villager
  attacker is player
  attacker's tool is lead
  cancel event

  leash victim to attacker
  send action bar "Custom villager leashing" to attacker
  remove 1 from item amount of attacker's tool if gamemode of attacker is not creative