options:
    discordChannelId: 695751303586119700
    recentAttackTime: 15 seconds

function capitalize(t: text) :: text:
    set {_first_char} to first character of {_t}
    set {_remaining_chars} to last (length of {_t} - 1) characters of {_t}
    set {_output} to "%{_first_char} in upper case%%{_remaining_chars}%"
    return {_output}

on script load:
    loop {recently_attacked::*}:
        delete {recently_attacked.%{recently_attacked::%loop-index%}%}
        remove {recently_attacked::%loop-index%} from {recently_attacked::*}

on death of villager:
    set {_murder_variations::*} to "murdered", "assassinated", "brutally slaughtered", "nuked", "killified", "terminated", "deprecated", "annihilated", and "deleted"
    set {_villager_name} to display name of victim otherwise "Villager"
    set {_id} to {entityid.%victim's entity uuid%} otherwise "[unassigned]"

    if attacker is set:
        set {_attacker_name} to display name of attacker otherwise capitalize("%attacker%")
        set {death_msg} to "%{_villager_name}% was %random element out of {_murder_variations::*}% by %{_attacker_name}% (%{_id}%)"
    else:
        set {death_msg} to "%{_villager_name}% died from %damage cause% (%{_id}%)"


    send ":skull: **%{death_msg}%  |  [COORDS: %x-coordinate of victim%, %y-coordinate of victim%, %z-coordinate of victim% | WORLD: %world of victim%]**" to channel with id "{@discordChannelId}" with "Cheezy"
    broadcast "%{death_msg}% %nl%§7§o[COORDS: %x-coordinate of victim%, %y-coordinate of victim%, %z-coordinate of victim% | WORLD: %world of victim%]"
    

# on damage:
#     victim is villager
#     add victim's entity uuid to {recently_attacked::*} # make it so that if the server stops before the wait time is over, that the variable doesnt clog everything and have the server delete it on startup
#     set {recently_attacked.%victim's entity uuid%} to display name of attacker otherwise capitalize("%attacker%")
#     wait {@recentAttackTime}
#     delete {recently_attacked.%victim's entity uuid%}
#     remove victim's entity uuid from {recently_attacked::*}