options:
  prefix: §f#§e[Propaganda] §f
  interval: 30 seconds

on script load:
  delete {propaganda::*}


  add """I guess in 2018 people just really liked to fuck their cats."" -Jasper 2020" to {propaganda::*}
  add """If you [have] large homosexual urges, you know who to call."" -Maxford 2021" to {propaganda::*}
  add """I constantly go to nightclubs. There's nothing I like more."" -Jasper 2020" to {propaganda::*}
  add """Thank you for being test subjects in this civilian genocide."" -Lucas 2020" to {propaganda::*}
  add """Lemme bring you out of sight to harass you real quick."" -Lucas 2020" to {propaganda::*}
  add """My connection is dying and my pants just disappeared."" -Jakob 2021" to {propaganda::*}
  add """I dream for Kim Jong Un to slap me with a salmon."" -Jasper 2021" to {propaganda::*}
  add """Hey Liam do you want my cocaine? I don't want it."" -Hoang 2021" to {propaganda::*}
  add """It didn't have water because I didn't place water."" -Liam 2020" to {propaganda::*}
  add """Now I just need a place for my hentai basement."" -Lucas 2020" to {propaganda::*}
  add """Uaguaghaaaauaaughhghwaaeoeueeuang'aang"" -Liam and Hoang 2020" to {propaganda::*}
  add """Love is in the air with all these cows fricking."" -Liam 2021" to {propaganda::*}
  add """Ooh. I'm gonna shoot a baby. Yeah, baby dead."" -Jasper 2021" to {propaganda::*}
  add """Okay have sex in front of me. Incest is great."" -Lucas 2020" to {propaganda::*}
  add """You can never have too many hentai."" -Liam and Jasper 2021" to {propaganda::*}
  add """You see, doing teachers would be really fun."" -Jakob 2021" to {propaganda::*}
  add """I just wanna duck this cow. Why is it so hard?"" -Asa 2021" to {propaganda::*}
  add """One of the zombies turned into a zombie."" -Hoang 2020" to {propaganda::*}
  add """I think anal machines are pretty useful."" -Lucas 2021" to {propaganda::*}
  add """Is this guy naked? I really hope he is."" -Jakob 2021" to {propaganda::*}
  add """I'm doing this because uwu senpai. Owl!"" -Hoang 2021" to {propaganda::*}
  add """Nothing makes me more horny than food!"" -Jasper 2021" to {propaganda::*}
  add """Yeah, man. I punched ten babies today."" -Hoang 2021" to {propaganda::*}
  add """Civilian genocide. That's all I need."" -Lucas 2020" to {propaganda::*}
  add """Do you think shrek has super sperm?"" -Jasper 2021" to {propaganda::*}
  add """Yes, theft, my favourite activity."" -Lucas 2020" to {propaganda::*}
  add """Can you please don't not do that?"" -Jasper 2020" to {propaganda::*}
  add """I'm kind of a little indecisive."" -Toby 2021" to {propaganda::*}
  add """My pp was cut off my Hypixel."" -Jasper 2021" to {propaganda::*}
  add """100%% would smash."" -Jasper 2021, on Shrek" to {propaganda::*}
  add """Hey, are you a black Canadian?"" -Toby 2021" to {propaganda::*}
  add """I said notice me senpai! Uwu!"" -Liam 2021" to {propaganda::*}
  add """Gotta love that vacuum ASMR."" -Jakob 2021" to {propaganda::*}
  add """Okay someone send me hentai."" -Lucas 2020" to {propaganda::*}
  add """I like to support murderers."" -Liam 2020" to {propaganda::*}
  add """I §lwill §rpunch a child."" -Jasper 2021" to {propaganda::*}
  add """I think communism was good"" -Liam 2020" to {propaganda::*}
  add """Genocide's a smart idea."" -Jasper 2020" to {propaganda::*}
  add """No, I'll fist §oyou§r."" -Jasper 2021" to {propaganda::*}
  add """I just punched a baby."" -Hoang 2021" to {propaganda::*}
  add """I'm making them horny."" -Toby 2021" to {propaganda::*}
  add """Hentai is a necessity."" -Asa 2021" to {propaganda::*}
  add """I am a pig kink."" -Jakob 2021" to {propaganda::*}
  add """Allah the Pinata"" -Hoang 2020" to {propaganda::*}
  add """I am very high."" -Lucas 2020" to {propaganda::*}
  add "It is illegal to break the law." to {propaganda::*}
  add "Je suis une vache explosive." to {propaganda::*}
  add "Ever tried to shear a bee?" to {propaganda::*}
  add "Ignorance is strength." to {propaganda::*}
  add "Je suis une chenille." to {propaganda::*}
  add "Do all the drugglez." to {propaganda::*}
  add "Don't do X-Ray." to {propaganda::*}
  add "Love is fake." to {propaganda::*}
  add "Hail Santa." to {propaganda::*}

every {@interval}:
  send action bar "{@prefix}%random element out of {propaganda::*}%" to all players